### ISSUE TITLE
Is there any new menu to use 2 interface?

### ISSUE THREAD

**Issue by herdy25** [xpz3/airgeddonplugins#2]
i am sorry may i know how to know if this plugin already running in airgeddon? coz i already tried and nothing changed on evil twin. no option to use more than 1 interface

**Comment by xpz3** [comment]
Are you the one from discord who got it resolved by updating airgeddon?

**Comment by herdy25** [comment]
Yuph that's me.. Sorry not closed the issue on github. Thank you for your
help
