### ISSUE TITLE
Sorry to open this here 

### ISSUE THREAD

**Issue by dr1408** [xpz3/airgeddonplugins#4]
I didn find a way to contact you just wanna ask did you get wifipumpkin3 working and sharing internet on nethunter and can i have your discord to talk about it ?

**Comment by xpz3** [comment]
I haven't used wifipumpkin ever but looks like you're having issues with iptables.. iirc, the tool didn't support nft and you had to use old iptables version.. easy way would be to purge current and install an old version. Or rename current iptables to something else and rename iptables-legacy and similar binaries (iptables-legacy-save) by removing -legacy from them. So iptables-legacy would become iptables and iptables-legacy-save would become iptables-save. There are a couple of others as well.. if wifipumpkin has internet sharing options, this would fix it

**Comment by dr1408** [comment]
Already downgraded iptables .. still same problems .. it has internet sharing option but it show the interface to share internet As none not wlan0 which is the mobile internet

**Comment by xpz3** [comment]
You dont need internet for evil twin. If you want to run evil twin, try airgeddon which is actively maintained and evil twin works perfectly.
